name:                hspec-terminal-bug
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hspec-terminal-bug#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  hspec-terminal-bug:
    source-dirs:      src
    main:             Main.hs

tests:
  wolf-test:
    main:             Main.hs
    source-dirs:      tests
    dependencies:
      - tasty >= 1.1.0.2 && < 2
      - tasty-hspec >= 1.1.5 && < 2
      - tasty-discover >= 4.2.1 && < 5
